###
# This is the place to override the deploy cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "play2/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

